/*
 * program.c
 *
 *  Created on: Aug 20, 2024
 *      Author: Maryam
 */

////#include "../MCAL/DIO/INTERFACE.h"
//#include "../MCAL/UART/interface.h"
#include "../HAL/LCD/interface.h"
#include "interface.h"
#include <util/delay.h>


u8 DETECT = 0;
u8 DETECT2 = 0;
u8 DATA_RECEIVED = 0;

void initialize_hardware(struct lcd_config *LCD2) {
    // Initialize LCD
    LCD_INTI(LCD2);

    // Initialize DIO Pins
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTB, TOGGLE_PIN, INPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTB, TOGGLE_PIN2, INPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTC, MOTOR_CW_PIN, OUTPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTC, MOTOR_CCW_PIN, OUTPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTC, MOTOR_CW_PIN2, OUTPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTC, MOTOR_CCW_PIN2, OUTPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTC, EN1_PIN, OUTPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTC, EN2_PIN, OUTPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTC, BUZZER_PIN, OUTPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTB, DOOR_MOTOR_PIN1, OUTPUT);
    DIO_MCAL_SET_PIN_DIRECTION(SER_PPORTB, DOOR_MOTOR_PIN2, OUTPUT);

    // Initialize UART
    UART_INTI();
}

void stop_train() {
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, MOTOR_CW_PIN, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, MOTOR_CCW_PIN, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, MOTOR_CW_PIN2, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, MOTOR_CCW_PIN2, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, EN1_PIN, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, EN2_PIN, LOW);
}

void start_train() {
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, MOTOR_CW_PIN, HIGH);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, MOTOR_CCW_PIN, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, MOTOR_CW_PIN2, HIGH);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, MOTOR_CCW_PIN2, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, EN1_PIN, HIGH);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTC, EN2_PIN, HIGH);

}

void open_door() {
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTB, DOOR_MOTOR_PIN1, HIGH);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTB, DOOR_MOTOR_PIN2, LOW);
}

void close_door() {
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTB, DOOR_MOTOR_PIN1, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTB, DOOR_MOTOR_PIN2, HIGH);
}

void handle_emergency(struct lcd_config *LCD2) {
    WRITE_STRING(LCD2, "DANGEROUS!");
    _delay_ms(2000);
    stop_train();
    _delay_ms(6000);
    CLEAR_DIS(LCD2);
    LCD_RETURN_HOME(LCD2);
    _delay_ms(6000);
    DATA_RECEIVED = 0;
}

void handle_door_operations() {

    DIO_MCAL_SET_PIN_VALUE(SER_PPORTB, DOOR_MOTOR_PIN1, LOW);
    DIO_MCAL_SET_PIN_VALUE(SER_PPORTB, DOOR_MOTOR_PIN2, LOW);


}

void get_detect2(u8 *U8DETECT2){
	 DIO_MCAL_GET_PIN_VALUE(SER_PPORTB, TOGGLE_PIN2, U8DETECT2);
}
void get_detect(u8 *U8DETECT){
	 DIO_MCAL_GET_PIN_VALUE(SER_PPORTB, TOGGLE_PIN, U8DETECT);
}
//void receive_emergency(u8 *U8DATA_RECEIVED){
//
//    UART_RECEIVE(&U8DATA_RECEIVED);
//}
