/*
 * program.c
 *
 *  Created on: Jul 30, 2024
 *      Author: Maryam
 *
 *
 */

#include"interface.h"
#include "config.h"


void KEYPAD_INITI()
{
	u8 ROW_INDEX ;
	u8 COL_INDEX ;


	for(ROW_INDEX = KEYPAD_ROW_0 ; ROW_INDEX <= KEYPAD_ROW_3 ; ROW_INDEX++){

		DIO_MCAL_SET_PIN_DIRECTION(KEYPAD_PORT , ROW_INDEX , OUTPUT_PIN);
		DIO_MCAL_SET_PIN_VALUE( KEYPAD_PORT,  ROW_INDEX , HIGH);



	}
	for(COL_INDEX = KEYPAD_COL_0 ; COL_INDEX <= KEYPAD_COL_3 ; COL_INDEX++){

			DIO_MCAL_SET_PIN_DIRECTION(KEYPAD_PORT , COL_INDEX , INPUT_PIN);
			DIO_MCAL_SET_PIN_VALUE( KEYPAD_PORT,  COL_INDEX , HIGH);


		}

}
void KEYPAD_GET_BUTT(u8 *U8CHAR)
{
	u8 KEYPADARR[KEYPAD_ROW_NUM][KEYPAD_COL_NUM] = KEYPAD_ARR;

	u8 LOCAL_COL_INDEX = 0;
	u8 LOCAL_ROW_INDEX = 0;



	u8 LOCAL_COL_ARR[KEYPAD_COL_NUM] = {KEYPAD_COL_0, KEYPAD_COL_1,KEYPAD_COL_2,KEYPAD_COL_3};
	u8 LOCAL_RAW_ARR[KEYPAD_ROW_NUM] = {KEYPAD_ROW_0, KEYPAD_ROW_1,KEYPAD_ROW_2,KEYPAD_ROW_3};
	u8 LOCAL_STATE =1 ;

	for(LOCAL_ROW_INDEX =0 ;LOCAL_ROW_INDEX  < KEYPAD_ROW_NUM ; LOCAL_ROW_INDEX++){

		DIO_MCAL_SET_PIN_VALUE(KEYPAD_PORT ,LOCAL_RAW_ARR[LOCAL_ROW_INDEX] , LOW);
		for(LOCAL_COL_INDEX = 0 ; LOCAL_COL_INDEX < KEYPAD_COL_NUM; LOCAL_COL_INDEX++){

			DIO_MCAL_GET_PIN_VALUE(KEYPAD_PORTA , LOCAL_COL_ARR[ LOCAL_COL_INDEX], &LOCAL_STATE);
			if(LOCAL_STATE == KEYPAD_PRESSED){


				while (LOCAL_STATE == KEYPAD_PRESSED){

					DIO_MCAL_GET_PIN_VALUE(KEYPAD_PORTA , LOCAL_COL_ARR[ LOCAL_COL_INDEX], &LOCAL_STATE);


				}
				*U8CHAR = KEYPADARR[LOCAL_ROW_INDEX][LOCAL_COL_INDEX];

			}

		}
		DIO_MCAL_SET_PIN_VALUE(KEYPAD_PORT , LOCAL_RAW_ARR[LOCAL_ROW_INDEX] , HIGH);

	}


}



